#!/bin/bash

set -e
set -u

worker_ready() {
    celery -A celery_configs.celery_app inspect ping
}

until worker_ready; do
  >&2 echo 'Celery workers not available'
  sleep 1
done

>&2 echo 'Celery workers are available'

celery -A celery_configs.celery_app \
    --broker="${CELERY_BROKER}" \
    flower
